import enum


class peptide_const(enum.auto):

    CONST_PEPTIDE_MIN_LENGTH = 2
    CONST_PEPTIDE_MAX_LENGTH = 50
    CONST_PEPTIDE_MAX_VALUE = 89
    CONST_PEPTIDE_MIN_VALUE = 65
    CONST_GENES = "ACDEFGHIKLMNPQRSTVWY"
    CONST_GENE_TYPES = 20
